CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(1000) NOT NULL,
    author_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_events FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_comments_users FOREIGN KEY (author_id) REFERENCES users (id)
);